Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "public_network"

  config.vm.synced_folder "../", "/var/www/html"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 apache2-utils
    
    cp /vagrant/.htpasswd /var/www/html/.htpasswd
    
    echo 'AuthType Basic\nAuthName "Restricted Area"\nAuthUserFile /var/www/html/.htpasswd\nRequire valid-user' > /var/www/html/.htaccess

    cp /vagrant/000-default.conf /etc/apache2/sites-available/000-default.conf

    cp /vagrant/404.html /var/www/html/404.html
    cp /vagrant/500.html /var/www/html/500.html
    cp /vagrant/403.html /var/www/html/403.html

    a2enmod status
    
    systemctl restart apache2

    chmod -R 755 /var/www/html

    apt-get install -y apache2-utils

    echo "Realizando pruebas de rendimiento con 100 usuarios y 1000 peticiones..."
    ab -n 1000 -c 100 http://localhost/ > /var/www/html/ab_100_1000.txt

    echo "Realizando pruebas de rendimiento con 1000 usuarios y 1000 peticiones..."
    ab -n 1000 -c 1000 http://localhost/ > /var/www/html/ab_1000_1000.txt

  SHELL
end