Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "public_network"

  config.vm.synced_folder "../", "/var/www/html"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    
    chmod -R 755 /var/www/html
  SHELL
end
